// This code is available on the terms of the project LICENSE.md file,
// also available online at https://blueoakcouncil.org/license/1.0.0.

// verifymm is a tool to verify market making proofs. It has two modes:
//
// verify: Takes a proof file generated by the mmproof RPC command and verifies
// that all order and match signatures are valid, then generates a coverage
// report identifying any gaps and deficiencies.
//
// genreport: Takes a JSON coverage report (output from verify mode) and generates
// a PDF report with summary stats, coverage graph, and unclosed orders.
package main

import (
	"errors"
	"fmt"
	"os"

	"decred.org/dcrdex/dex"
)

// CoverageReport is the JSON output of the verification.
type CoverageReport struct {
	// Input parameters
	StartTimeMs      uint64  `json:"startTimeMs"`
	EndTimeMs        uint64  `json:"endTimeMs"`
	EpochDurMs       uint64  `json:"epochDurMs"`
	RequiredQty      float64 `json:"requiredQty"`
	MaxSpreadPct     float64 `json:"maxSpreadPct,omitempty"`
	ConversionFactor uint64  `json:"conversionFactor"`
	BaseAssetID      uint32  `json:"baseAssetId"`
	BaseAssetSymbol  string  `json:"baseAssetSymbol"`
	QuoteAssetID     uint32  `json:"quoteAssetId"`
	QuoteAssetSymbol string  `json:"quoteAssetSymbol"`
	AccountID        string  `json:"accountId"`

	// Verification results
	ProofValid bool   `json:"proofValid"`
	ProofError string `json:"proofError,omitempty"`

	// Coverage summary
	TotalEpochs       uint64 `json:"totalEpochs"`
	BuyCoveredEpochs  uint64 `json:"buyCoveredEpochs"`
	SellCoveredEpochs uint64 `json:"sellCoveredEpochs"`

	// Time series data for graphing
	TimeSeries []*TimePoint `json:"timeSeries,omitempty"`

	// Unclosed orders - orders that are neither fully matched, cancelled, nor revoked
	UnclosedOrders []dex.Bytes `json:"unclosedOrders,omitempty"`
}

// TimePoint represents the order book state at a point in time.
type TimePoint struct {
	EpochNum uint64 `json:"epochNum"`

	// BuyQty / SellQty are the quantities considered for coverage evaluation.
	// If MaxSpreadPct > 0, these are "in-band" quantities based on the midpoint
	// and spread filter; if MaxSpreadPct == 0, they are the total book quantities.
	BuyQty  uint64 `json:"buyQty"`
	SellQty uint64 `json:"sellQty"`

	// Additional debug/audit fields.
	TotalBuyQty  uint64  `json:"totalBuyQty,omitempty"`
	TotalSellQty uint64  `json:"totalSellQty,omitempty"`
	BestBidRate  uint64  `json:"bestBidRate,omitempty"`
	BestAskRate  uint64  `json:"bestAskRate,omitempty"`
	MidRate      uint64  `json:"midRate,omitempty"`
	SpreadPct    float64 `json:"spreadPct,omitempty"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		os.Exit(1)
	}
}

func run() error {
	if len(os.Args) < 2 {
		printUsage()
		return errors.New("mode required: verify or genreport")
	}

	mode := os.Args[1]
	// Remove mode from args for flag parsing
	os.Args = append(os.Args[:1], os.Args[2:]...)

	switch mode {
	case "verify":
		return runVerify()
	case "genreport":
		return runGenReport()
	default:
		printUsage()
		return fmt.Errorf("unknown mode: %s", mode)
	}
}

func printUsage() {
	fmt.Fprintln(os.Stderr, `Usage: verifymm <mode> [options]

Modes:
  verify      Verify a proof file and generate a JSON coverage report
  genreport   Generate a PDF report from a coverage report

Run 'verifymm <mode> -help' for mode-specific options.`)
}
